---
os: linux
dist: jammy
language: python
python:
  - '3.12'
before_install:
  - pip install --upgrade pip setuptools
branches:
  only:
    - main
jobs:
  include:
    - name: Check YAML format
      install:
        - pip install tox
      script:
        - tox -e yamllint
    - name: Check Markdown Format
      install:
        - pip install tox
      script:
        - tox -e pymarkdown
    - name: Check Gherkin format
      language: node_js
      node_js: 22
      before_install: skip
      install:
        - npm install gherkin-lint
      script:
        - npx gherkin-lint
    - name: Check Python Format
      install:
        - pip install tox
      script:
        - tox -e flake8
    - name: Check Bash format
      install:
        - pip install tox
      script:
        - tox -e shellcheck
    - name: Test
      install:
        - pip install tox
      script:
        - tox -e test
    - name: Behave
      install:
        - pip install tox
      script:
        - tox -e behave
    - name: Check migrations
      install:
        - pip install tox
      script:
        - tox -e checkmigrations
    - name: Check django deploy settings
      install:
        - pip install tox
      script:
        - tox -e checkdeploy
    - stage: Integration Test
      # if: branch =~ /^(release)/
      name: Check nginx configuration
      install:
        - pip install tox
      script:
        - docker network create nginx-bridge
        - git clone https://github.com/i3thuan5/Formosan-AI.git
        - cd Formosan-AI/
        - echo ASR_VIRTUAL_HOST=localhost > .env
        - echo ASR_KALDI_VIRTUAL_HOST=localhost >> .env
        - echo TTS_VIRTUAL_HOST=localhost >> .env
        - echo MT_VIRTUAL_HOST=localhost >> .env
        - sed '/deploy/,+6d' -i deploy/docker-compose-production.yml
        - >
          docker compose -f docker-compose.yml -f deploy/docker-compose-production.yml
          up -d --quiet-pull > /dev/null
        - cd ..
        - mkdir secrets
        - cp testdata/random-key.txt secrets/django_secret_key.txt
        - cp testdata/random-key.txt secrets/postgres_passwd.txt
        - cp testdata/sentry-fake-key.txt secrets/sentry_dsn.txt
        - docker compose pull --quiet > /dev/null
        - docker compose build --quiet > /dev/null
        - sleep 6m
        - tox -e checknginx
      after_failure:
        - cd Formosan-AI/
        - docker compose logs
