services:

  nginx:
    image: nginx:1.28.0-alpine
    depends_on:
      - gunicorn
      - django-static
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      - nginx-bridge
      - gunicorn-bridge
    restart: always
    volumes:
      - "staticfiles:/staticfiles/"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"

  gunicorn:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment: &django_envs
      DJANGO_SECRET_KEY: /run/secrets/django_secret_key
      DJANGO_ALLOW_HOSTS: ${VIRTUAL_HOST}
      POSTGRES_PASSWORD: /run/secrets/postgres_passwd
    networks:
      - gunicorn-bridge
      - postgres-bridge
    restart: always
    secrets: &django_secrets
      - django_secret_key
      - postgres_passwd

  django-static:
    build: .
    command: ["python", "manage.py", "collectstatic", "--noinput"]
    environment: *django_envs
    network_mode: none
    restart: no
    secrets: *django_secrets
    user: "root"
    volumes:
      - "staticfiles:/staticfiles/"

  postgres:
    image: postgres:18.0-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/postgres_passwd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_period: "10s"
      start_interval: "1s"
      interval: "10s"
      timeout: "5s"
    labels:
      - "backup.postgres=true"
    networks:
      - postgres-bridge
    restart: always
    secrets:
      - postgres_passwd
    volumes:
      - "postgres-data:/var/lib/postgresql/18/docker"

networks:
  gunicorn-bridge:
  nginx-bridge:
    external: true
  postgres-bridge:

secrets:
  django_secret_key:
    environment: DJANGO_SECRET_KEY
  postgres_passwd:
    environment: POSTGRES_PASSWD_SECRET

volumes:
  postgres-data:
  staticfiles:
