services:
  # nginx-proxy:
  #   image:
  #   ports:
  #     - 127.0.0.1:80:80

  # nginx:
  #   image:
  #   volumes:
  #     - static

  django-gunicorn:
    build: .
    secrets:
      - django_secret_key
      - postgres_passwd
    volumes:
      - "staticfiles:/staticfiles/"
    environment:
      DJANGO_SECRET_KEY: /run/secrets/django_secret_key
      VIRTUAL_HOST: "127.0.0.1"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: /run/secrets/postgres_passwd
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18.0-alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/18/docker"
    secrets:
      - postgres_passwd
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: /run/secrets/postgres_passwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: "10s"
      timeout: "5s"
      retries: 5
    restart: always


volumes:
  postgres-data:
  staticfiles:

# network:
  # enable_ipv4
  # enable_ipv6

secrets:
  postgres_passwd:
    environment: POSTGRES_PASSWD_SECRET
  django_secret_key:
    environment: DJANGO_SECRET_KEY

# secrets.*.environment：當.env沒定義該變數，就會擋下。但空字串不會擋。
# 問題四：教典有加label