[tox]
skipsdist = True

[flake8]
max-line-length = 79
exclude =
    .git
    .tox
    venv
per-file-ignores =
    autuan/autuan/settings-tsiunnsuann.py:E501
    autuan/autuan/settings.py:E501

[testenv:yamllint]
deps =
    yamllint
commands =
    yamllint .

[testenv:flake8]
deps =
    flake8
commands =
    flake8 . --show-source --count

[testenv:pymarkdown]
deps =
    pymarkdownlnt
commands =
    pymarkdown \
        --strict-config \
        --disable-rules md013,md029 \
        scan .
    pymarkdown \
        --strict-config \
        --disable-rules MD041 \
        scan .github/*

[testenv:shellcheck]
allowlist_externals =
    bash
commands =
    bash shellcheck.sh

[testenv:test]
changedir =
    autuan
deps =
    -rrequirements-dev.txt
commands =
    python manage.py test {posargs}

[testenv:behave]
deps =
    -rrequirements-dev.txt
    behave
commands =
    python -m behave --no-skipped {posargs}

[testenv:checkmigrations]
deps =
    -rrequirements-dev.txt
changedir =
    autuan
commands =
    python -Wa manage.py makemigrations bangtsam --check

[testenv:checkdeploy]
deps =
    -rrequirements-prod.txt
changedir =
    autuan
setenv =
    TOX_CHECKDEPLOY = True
    DJANGO_SETTINGS_MODULE = autuan.settings-tsiunnsuann
    DJANGO_ALLOW_HOSTS = localhost.ithuan.tw
    DJANGO_SECRET_KEY_FILE = ../testdata/random-key.txt
    POSTGRES_PASSWORD_FILE = ../testdata/random-key.txt
    SENTRY_DSN_FILE = ../testdata/sentry-fake-key.txt
commands =
    python -Wa manage.py check --database default
    python -Wa manage.py check --deploy --fail-level WARNING

[testenv:checknginx]
allowlist_externals =
    docker
commands =
    docker image pull --quiet nginx:1.28.0-alpine
    docker compose run --rm nginx nginx -t
