[tox]
skipsdist = True

[flake8]
max-line-length = 79
exclude =
    .git
    .tox
    venv
per-file-ignores =
    autuan/autuan/settings-tsiunnsuann.py:E501
    autuan/autuan/settings.py:E501

[testenv:yamllint]
deps =
    yamllint
commands =
    yamllint .

[testenv:flake8]
deps =
    flake8
commands =
    flake8 . --show-source --count

[testenv:pymarkdown]
deps =
    pymarkdownlnt
commands =
    pymarkdown \
        --strict-config \
        --disable-rules md013,md029 \
        scan .
    pymarkdown \
        --strict-config \
        --disable-rules MD041 \
        scan .github/*

[testenv:shellcheck]
allowlist_externals =
    bash
commands =
    bash shellcheck.sh

[testenv:test]
changedir =
    autuan
deps =
    -rrequirements-dev.txt
commands =
    python manage.py test {posargs}

[testenv:behave]
deps =
    -rrequirements-dev.txt
    behave
commands =
    python -m behave --no-skipped {posargs}

[testenv:checkmigrations]
deps =
    -rrequirements-dev.txt
changedir =
    autuan
commands =
    python -Wa manage.py makemigrations bangtsam --check

[testenv:checkdeploy]
deps =
    -rrequirements-prod.txt
changedir =
    autuan
setenv =
    DJANGO_SECRET_KEY = Just^%For*CheckDeploy6e/9fe28bc8ef5_1e0ec407c935c7/221e1e4
    VIRTUAL_HOST = localhost.ithuan.tw
    TOX_CHECKDEPLOY = True
commands =
    python -Wa manage.py check --database default
    python -Wa manage.py check --deploy --settings=autuan.settings-tsiunnsuann \
        --fail-level WARNING
