# Generated by Django 5.2.6 on 2025-10-09 02:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


WAGTAILCORE_PAGE = 'wagtailcore.page'


class Migration(migrations.Migration):

    dependencies = [
        ('bangtsam', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to=WAGTAILCORE_PAGE)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(WAGTAILCORE_PAGE,),
        ),
        migrations.CreateModel(
            name='ApplicationFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to=WAGTAILCORE_PAGE)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(WAGTAILCORE_PAGE,),
        ),
        migrations.CreateModel(
            name='FeedbackPage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to=WAGTAILCORE_PAGE)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(WAGTAILCORE_PAGE,),
        ),
        migrations.CreateModel(
            name='IntroPage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to=WAGTAILCORE_PAGE)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(WAGTAILCORE_PAGE,),
        ),
        migrations.CreateModel(
            name='TermsOfUsePage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to=WAGTAILCORE_PAGE)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(WAGTAILCORE_PAGE,),
        ),
    ]
