# Generated by Django 5.2.6 on 2025-10-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangtsam', '0004_copyrightpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackpage',
            name='feedbackurl',
            field=models.URLField(blank=True, help_text='意見回饋的Google表單連結'),
        ),
    ]
