# Generated by Django 5.2.6 on 2025-10-10 09:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangtsam', '0007_alter_feedbackpage_feedbackurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformpage',
            name='sample',
            field=wagtail.fields.StreamField([('sample_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('tribe', 0), ('sample_text', 0), ('translation_text', 0), ('audio', 1)]], {})}, default=[('sample_block', {'audio': None, 'sample_text': '', 'translation_text': '', 'tribe': ''})], null=True),
        ),
    ]
