# Generated by Django 5.2.6 on 2025-10-11 04:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangtsam', '0008_applicationformpage_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformpage',
            name='sample',
            field=wagtail.fields.StreamField(
                [('sample_block', 2)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.documents.blocks.DocumentChooserBlock',
                        (), {}),
                    2: ('wagtail.blocks.StructBlock', [[
                        ('tribe', 0), ('sample_text', 0),
                        ('translation_text', 0), ('audio', 1)]], {})
                }, null=True),
        ),
    ]
