# Generated by Django 5.2.6 on 2025-10-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangtsam', '0009_alter_applicationformpage_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformpage',
            name='sample_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
