# Generated by Django 5.2.7 on 2025-12-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangtsam', '0010_applicationformpage_sample_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsPage',
        ),
    ]
