# The embedded DNS server address is 127.0.0.11.
# https://docs.docker.com/engine/network/#dns-services
resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    charset utf-8;
    charset_types *;
    client_header_timeout 5s;
    location /static/ {
        alias /staticfiles/;
    }
    location /media/ {
        alias /media/;
    }

    location /sapolita/ {
        set $sapolita asr:7860;
        proxy_pass  http://$sapolita$request_uri;
        proxy_set_header Host  $http_host;
        client_max_body_size 1G;
    }
    location /sapolita-kaldi/ {
        set $sapolita_kaldi asr-kaldi:7860;
        proxy_pass  http://$sapolita_kaldi$request_uri;
        proxy_set_header Host  $http_host;
        client_max_body_size 1G;
    }
    location /hnang-kari-ai-asi-sluhay/ {
        set $tts tts:7860;
        proxy_pass  http://$tts$request_uri;
        proxy_set_header Host  $http_host;
        client_max_body_size 1G;
    }
    location /kari-seejiq-tnpusu-ai-hmjil/ {
        set $mt mt:7860;
        proxy_pass  http://$mt$request_uri;
        proxy_set_header Host  $http_host;
    }
    location /favicon.ico {
        set $sapolita_kaldi asr-kaldi:7860;
        proxy_pass  http://$sapolita_kaldi$request_uri;
        proxy_set_header Host  $http_host;
    }
    location / {
        set $autuan gunicorn:8000;
        proxy_pass  http://$autuan$request_uri/;
        proxy_set_header Host  $http_host;
        client_max_body_size 10M;
    }
}
