upstream autuan {
    server gunicorn:8000;
}
upstream sapolita {
    server asr:7860;
}
upstream sapolita-kaldi {
    server asr-kaldi:7860;
}
upstream hnang-kari-ai-asi-sluhay {
    server tts:7860;
}
upstream kari-seejiq-tnpusu-ai-hmjil {
    server mt:7860;
}

server {
    listen 80;
    charset utf-8;
    charset_types *;
    client_header_timeout 5s;
    location /static/ {
        alias /staticfiles/;
    }
    location /media/ {
        alias /media/;
    }

    location /sapolita/ {
        proxy_pass  http://sapolita$request_uri;
        proxy_set_header Host  $http_host;
        client_max_body_size 1G;
    }
    location /sapolita-kaldi/ {
        proxy_pass  http://sapolita-kaldi$request_uri;
        proxy_set_header Host  $http_host;
        client_max_body_size 1G;
    }
    location /hnang-kari-ai-asi-sluhay/ {
        proxy_pass  http://hnang-kari-ai-asi-sluhay$request_uri;
        proxy_set_header Host  $http_host;
        client_max_body_size 1G;
    }
    location /kari-seejiq-tnpusu-ai-hmjil/ {
        proxy_pass  http://kari-seejiq-tnpusu-ai-hmjil$request_uri;
        proxy_set_header Host  $http_host;
    }

    location / {
        proxy_pass  http://autuan/;
        proxy_set_header Host  $http_host;
        client_max_body_size 10M;
    }
}
