"""
Django settings for autuan project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a-08yw3^i0tow6i2$=%5pjui6rhf&w8s%brem6%7lp)ae!8*w$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',
    'password_policies',
    'axes',

    'bangtsam',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'password_policies.middleware.PasswordExpirationMiddleware',
    'axes.middleware.AxesMiddleware',
    'bangtsam.middleware.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'autuan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bangtsam.context_processors.theh_wagtail_pages',
                'bangtsam.context_processors.theh_ai_url',
                'bangtsam.context_processors.theh_ga_id',
            ],
        },
    },
]

WSGI_APPLICATION = 'autuan.wsgi.application'


# Django-axes related
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_ENABLE_ACCESS_FAILURE_LOG = True

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'password_policies.password_validation.ComplexityValidator',
    },
    {
        'NAME': 'password_policies.password_validation.ReusedPasswordValidator',
    },
    {
        'NAME': 'password_policies.password_validation.MinimumChangeIntervalValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session related

SESSION_COOKIE_AGE = 60 * 30  # 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024  # 要比最大上傳量大一點才能上傳成功
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50

# Wagtail

WAGTAIL_SITE_NAME = '成果網站內容後台'
WAGTAILADMIN_BASE_URL = 'localhost'
WAGTAILIMAGES_EXTENSIONS = ['svg', 'png', 'jpg', 'webp', ]
WAGTAILIMAGES_MAX_UPLOAD_SIZE = 3 * 1024 * 1024
WAGTAILDOCS_EXTENSIONS = ['docx', 'odt', 'pdf', 'txt', 'wav', ]
WAGTAIL_PASSWORD_RESET_ENABLED = False  # 關閉「忘記密碼？」連結
WAGTAILAPI_SEARCH_ENABLED = False
CUSTOM_WAGTAILDOCS_MAX_UPLOAD_SIZE = 5 * 1024 * 1024
WAGTAILDOCS_DOCUMENT_FORM_BASE = 'bangtsam.forms.document_base.CustomDocumentForm'


# Content Security Policy
# 由 bangtsam.middleware.ContentSecurityPolicyMiddleware 依路徑前綴擇一送出。

# 走後台政策的路徑前綴，其餘一律走前台政策。
CSP_ADMIN_PATH_PREFIXES = (
    '/katayalan/',  # Wagtail 內容後台
    '/kuanli/',     # Django admin
)

# 前台：站內模板零個 inline script、零個 inline style，
# 因此可以完全不用 'unsafe-inline' 與 'unsafe-eval'。
# frame-ancestors、form-action、base-uri 不會 fallback 到 default-src，
# 必須各自明寫，否則 ZAP 會判為 Wildcard Directive。
CSP_POLICY_FRONTEND = '; '.join((
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self'",
    # Bootstrap 的 CSS 以 data: URI 內嵌 SVG 圖示（navbar-toggler、btn-close 等）
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self'",
    # 內文以 wagtail embeds 內嵌 YouTube 影片
    "frame-src https://www.youtube.com",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
))

# 後台：Wagtail admin 的 inline script/style 由上游產生，我們無法在其標籤上
# 補 nonce，只能放寬。後台需登入，未認證的弱點掃描掃不到，
# 這條政策的目的是縱深防禦而非清除告警。
CSP_POLICY_BACKEND = '; '.join((
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "media-src 'self' blob:",
    "font-src 'self' data:",
    "connect-src 'self'",
    "worker-src 'self' blob:",
    # 後台預覽頁面是同源 iframe
    "frame-src 'self' https://www.youtube.com",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
))


# AI
SAPOLITA_ASR_URL = "/sapolita-kaldi/"
SAPOLITA_TTS_URL = "/hnang-kari-ai-asi-sluhay/"
SAPOLITA_TRANSLATE_URL = "/kari-seejiq-tnpusu-ai-hmjil/"

# GA
GA_MEASUREMENT_ID = os.environ.get('GA_MEASUREMENT_ID', '')
